### ISSUE TITLE
problem in jcenter

### ISSUE THREAD

**Issue by tmediaa** [freedomofdevelopers/fod#106]
سلام 
من تنظیمات مورد نظر رو در gradle.properties ثبت میکنم اما موقعی که میخوام که کتابخونه از gradle رو sync کنم خطا میده بطور مثال این کتابخونه 👍 

    compile 'com.github.datalink747:NiceNavigation:1.1'

میخواستم ببینم چجوری میشه این پراکسی رو روی jcenter اعمال کرد ؟

**Comment by behdad222** [comment]
@tmediaa ارور چیه؟

**Comment by tmediaa** [comment]
@behdad222 خطای Failed to resolve

`Error:(28, 13) Failed to resolve: com.github.datalink747:NiceNavigation:1.1
<a href="openFile:C:/Users/tmediaa/AndroidStudioProjects/AhmadianPicker/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>`

**Comment by behdad222** [comment]
من تست کردم مشکل نداشت
میشه تنظیماتتون رو هم بزارید
@tmediaa

**Comment by tmediaa** [comment]
build.gradle content: 

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "*********"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha9'
    compile 'com.github.datalink747:NiceNavigation:1.1'
    testCompile 'junit:junit:4.12'
}
`
gradle.properties content:

`systemProp.https.nonProxyHosts=*.jitpack.io, *.maven.org
systemProp.http.proxyHost=fod.backtory.com
systemProp.https.proxyPort=8118
ystemProp.http.proxyHost=fod.backtory.com
org.gradle.jvmargs=-Xmx1536m
systemProp.https.proxyHost=fod.backtory.com
systemProp.http.proxyPort=8118
`

**Comment by behdad222** [comment]
@tmediaa 
این خط رو پاک کن
jitpack و maven اضافه شدن و از پراکسی میتونند رد شند
اگر هم s تو خط زیر نیست اضافه کن
ystemProp.http.proxyHost

**Comment by tmediaa** [comment]
@behdad222 
`systemProp.http.proxyHost=fod.backtory.com
systemProp.https.proxyPort=8118
systemProp.https.proxyHost=fod.backtory.com
org.gradle.jvmargs=-Xmx1536m
systemProp.http.proxyPort=8118
`

الان با این تنظیمات هم باز همون خطای قبلی رو میده

**Comment by oraclenik** [comment]
این مشکل حل شده؟

**Comment by behdad222** [comment]
این کتاب خونه تو گیت‌هاب هست
و اصلا تو jcenter نباید باشه
باید ریپوزیتوری مورد نظر اضافه شه
