### ISSUE TITLE
SNI proxy?

### ISSUE THREAD

**Issue by fzerorubigd** [freedomofdevelopers/fod#140]
it is very cool to have a sniproxy (such as this https://github.com/dlundquist/sniproxy) for this selected domain, and add this domains into /etc/hosts (or equivalent  in mac/linux) so there is no need to set a proxy or use a proxy software. 

I can create (auto-generate) the config based on domains file for the endpoint, but since you must install 2 of them in your setup, for the first one (in Iran) you should create the config.(which is very straight forward).

Let me know if this is possible.

**Comment by oraclenik** [comment]
Hi dear foroud, It's a great idea. I'll test it ASAP. 
Thanks
