### ISSUE TITLE
2 domains

### ISSUE THREAD

**Issue by alitalebi7s** [freedomofdevelopers/fod#171]
موتور بازی سازی آنریل
.unrealengine.com
شبکه طراحان( کاربردیه برای فرانت دیزاینرها)
.behance.net

کاش میشد یوتیوب رو هم باز کنید درسته فیلتره ولی تمام سایتهایی که تو لیست هستند ویدئوهاشون رو با یوتیوب منتشر میکنند.

**Comment by alitalebi7s** [comment]
اگه فیلترباشه باید صفحه فیلترینگ بیاد بجاش. مطمئنید؟

**Comment by behdad222** [comment]
@alitalebi7s خوب میاد
