### ISSUE TITLE
Add *.imgur.com/*

### ISSUE THREAD

**Issue by KiarashS** [freedomofdevelopers/fod#175]
Please add `*.imgur.com/*`

`imgur` is used widely in stackexchange communities and stackoverflow.com for images hosting.

**Comment by behdad222** [comment]
filtered in Iran

**Comment by KiarashS** [comment]
@behdad222  Yes! This is role of fod to access `imgur` in Iran :)

**Comment by oraclenik** [comment]
متاسفانه اگر در ایران فیلتر باشه نمیتونیم فقط فنا تحریم :)
