### ISSUE TITLE
gitlab.com, splunk.com

### ISSUE THREAD

**Issue by mphj** [freedomofdevelopers/fod#181]
متاسفانه گیت لب هم بعد از کوچ به سمت گوگل کلود, از دستمون رفت ...

**Comment by behdad222** [comment]
گیت‌لب قبلا اضافه شده
مشکل splunk.com چی هست؟
من به صورت مستقیم بهش دسترسی دارم
@mphj

**Comment by mphj** [comment]
سلام, بله ممنون ولی gitlab رو چون داخل readme.md ندیدم درخواست دادم
و اینکه این سایت رو ملاحظه کنین لطفا https://mint.splunk.com/

**Comment by asedsami** [comment]
سلام. من با
proxychains
نتونستم وصل بشم. علت رو نمی‌دونم شاید اشتباه تنظیم کردم.
ممنون می‌شم راه‌نمایی کنین.

**/etc/proxychains.conf**

```
[ProxyList]
http 185.105.184.205 8118
```


proxychains4 git clone git@gitlab.com:<PATH_TO_PROJECT>.git project-name
```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib64/proxychains-ng/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
Cloning into 'backend'...
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  185.105.184.205:8118  ...  timeout
ssh: connect to host gitlab.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by behdad222** [comment]
git config --global http.proxy fodev.org:8118

@asedsami از این استفاده کن

**Comment by amirakhavan** [comment]
با تشکر از سرویس خوبتون و همچنین افزودن گیت‌لب 👍 برای باز کردن سایت گیت‌لب علاوه بر آدرس gitlab.com یکسری فایل‌های هم از سایت gitlab-static.net هستن که چون این آدرس در سرویس شما پشتیبانی نمیشه باعث شده سایت گیت‌لب بدرستی مشاهده نشه!

**Comment by morteza-pourEtemadi** [comment]
سلام و با تشکر از سرویس خوبتون
بنده از این دستور هم استفاده کردم
git config --global http.proxy fodev.org:8118
ولی بازم موقع 
push  و pull
با گیتلب مشکل دارم. درست نشد

**Comment by mphj** [comment]
سلام خدمت دوستانی که مشکل دارن هنوز با گیت لب
داخل فایل 
``` ~/.ssh/config ```
اگه وجود نداشت بسازیدش
محتوای داخلش رو این قرار بدید

``` sh
Host gitlab.com
nc -X connect -x fodev.org:8118 %h %p
```
@morteza-pourEtemadi   @asedsami

**Comment by asedsami** [comment]
@mphj 
واقعا ممنونم. این پیغام رو می‌گرفتم:
`nc: invalid option -- 'X'`
به این تغییر دادم و درست شد:
‍‍‍`ProxyCommand nc --proxy fodev.org:8118 %h %p`

**Comment by FareheSoheil** [comment]
ببخشید میشه تنظیماتش رو برای ویندوز هم بگید ؟
من کارم رو ویندوز گیره روی لینوکس نیست :(

**Comment by ghodsizadeh** [comment]
> سلام خدمت دوستانی که مشکل دارن هنوز با گیت لب
> داخل فایل
> `~/.ssh/config`
> اگه وجود نداشت بسازیدش
> محتوای داخلش رو این قرار بدید
> 
> ```shell
> Host gitlab.com
> ProxyCommand nc -X connect -x fodev.org:8118 %h %p
> ```
> 
> چک کنید که netcat نصب باشه
> 
> همچنین این کار رو هم انجام بدید
> [#181 (comment)](https://github.com/freedomofdevelopers/fod/issues/181#issuecomment-414278085)
> که برای کار با پروتکل http داخل گیت به مشکل نخورید
> 
> @morteza-pourEtemadi @asedsami

من بعد از انجام این تغییرات با خطای زیر مواجه می‌شم.
nc: Proxy error: "HTTP/1.1 200 Connection established"
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

درست مثل حالتی که sshkey رو به  gitlab معرفی نکرده باشیم.

کسی ایده‌ای داره که مشکل چجوری حل میشه؟

**Comment by mohsani** [comment]
متاسفانه اسپاتیفای کماکان مشکل داره و کار نمی‌کنه.

**Comment by behdad222** [comment]
@mohsani زیر ایشو مربوط به اسپاتیفای در موردش بپرس

**Comment by behdad222** [comment]
@FareheSoheil 
پیشنهاد اولم اینه که به لینوکس مهاجرت کنید
پیشنهاد دوم این لینکه https://stackoverflow.com/questions/22799825/using-git-on-windows-behind-an-http-proxy-without-storing-proxy-password-on-di
پیشنهاد سوم استفاده از یه چیزیه که کل سیستم رو رد کنه مثل پراکسی فایر و تنظیمات fod رو تو اون وارد کن

**Comment by hannanstd** [comment]
سلام دوستان
راهی برای ست کردن بر روی گیت لب رانر روی سرور های ایران هم هست؟

**Comment by behdad222** [comment]
@hannanstd برای پول گرفتن ایمیج توسط راننر همون کاری که برای داکر میکنی رو باید انجام بدی

**Comment by MostafaNobaghi** [comment]
> سلام خدمت دوستانی که مشکل دارن هنوز با گیت لب
سلام من همچنان نمیتونم pull بگیرم
