### ISSUE TITLE
Add Gitlab

### ISSUE THREAD

**Issue by Benjamin-s1** [freedomofdevelopers/fod#216]
Hi Thanks for this lovely movement.
please add gitlab.com to your list

**Comment by oraclenik** [comment]
Hi, Thanks
gitlab.com is already in the list :)

**Comment by Benjamin-s1** [comment]
> 
> 
> Hi, Thanks
> gitlab.com is already in the list :)

why in android studio i cant access it ? but when i use anti filter software it is accessable ?
with this proxy it isnt :(

**Comment by behdad222** [comment]
@Benjamin-s1 use git proxy
https://github.com/freedomofdevelopers/fod#git
