### ISSUE TITLE
این پروکسی رو چطوری برا npm و ری اکت فعال کنیم ؟

### ISSUE THREAD

**Issue by artinZareie** [freedomofdevelopers/fod#244]
این پروکسی رو چطوری برا npm و ری اکت فعال کنیم ؟

**Comment by geminorum** [comment]
<div dir="rtl">
اگر برای npm تنظیم بشه، دیگه yarn کار نمیکنه. یه راه‌حل اینه که yarn هم به لیست اضافه بشه.
</div>

**Comment by behdad222** [comment]
@geminorum مشکلی نیست اضافه شه

**Comment by oraclenik** [comment]
@behdad222 is this resolved?

**Comment by behdad222** [comment]
@oraclenik i think

**Comment by geminorum** [comment]
must add npm and yarn to the domain list.

**Comment by behdad222** [comment]
@geminorum domain?

**Comment by SinaKarimi7** [comment]
@artinZareie 
In Unix-based systems (such as Ubuntu, Mac os, etc) make "config" file in ".ssh" folder and put this line into it.

`Host gitlab.com`
`ProxyCommand nc -X connect -x fodev.org:8118 %h %p`
