### ISSUE TITLE
Google search console

### ISSUE THREAD

**Issue by webpajooh** [freedomofdevelopers/fod#248]
Hi.
I can't open this link:
> https://www.google.com/appserve...

It's for **Google Search Console**

**Comment by oraclenik** [comment]
Its 404 🤔

**Comment by webpajooh** [comment]
No, i got 403 error:

> Your client does not have permission to get URL /appserve from this server. That’s all we know.

**Comment by behdad222** [comment]
@oraclenik  خود گوگل هست
نه ساب دومین
این رو اضافه نکردیم

**Comment by oraclenik** [comment]
هنوزم لینک به من ۴۰۴ میده 
فعلا میبندم این رو اگر مشکل با فاد حل میشه اطلاعات بیشتری بهمون بدید
ولی نمی‌تونیم خود دامنخ گوگل رو اضافه کنیم
