### ISSUE TITLE
مشکل در اتصال به پروکسی : خطا ۵۰۳

### ISSUE THREAD

**Issue by ashkanRmk** [freedomofdevelopers/fod#276]
سلام
هنگام اتصال به گیتلب با پروکسی به صورت کامندلاین این ارور داده میشه:

fatal: unable to access 'https://gitlab.com/Test/tes.git/': Received HTTP code 503 from proxy after

**Comment by oraclenik** [comment]
سلام مشکل حل شد

**Comment by rikidevdroid** [comment]
سلام، کلا هیچ سایتی بالا نمیاد با اکستشن کروم

**Comment by oraclenik** [comment]
من دقیقا همین الان همین کامنت رو دارم با  
Switchy Omega 
روی کروم مینویسم مشکلی ندارم
یک بار تظیماتتمون رو چک کنید

**Comment by rikidevdroid** [comment]
چک کردم، نمیاد

**Comment by rikidevdroid** [comment]
developers.android نمیاد

**Comment by majidnavaeeyan** [comment]
سلام
من برای استفاده از اندروید استودیو تنظیمات شما رو وارد کردم ولی نمی تونه ازش استفاده  کنه.
فعلا داره در قسمت پاین دانلود زیر رو انجام می دهو مدتیه که  داره می چرخه .

Download https://services.gradle.org/distributions/gradle-4.10.1-all.zip | 9 m 25 s 317 ms

میشه راهنماییم کنید ؟

**Comment by majidnavaeeyan** [comment]
> سلام
> من برای استفاده از اندروید استودیو تنظیمات شما رو وارد کردم ولی نمی تونه ازش استفاده کنه.
> فعلا داره در قسمت پاین دانلود زیر رو انجام می دهو مدتیه که داره می چرخه .
> 
> Download https://services.gradle.org/distributions/gradle-4.10.1-all.zip | 9 m 25 s 317 ms
> 
> میشه راهنماییم کنید ؟

الان هم به ارور خورد و ارور زیر رو داد. لطفا راهنماییم کنید.
تشکر

SSL peer shut down incorrectly |  
-- | --

**Comment by behdad222** [comment]
یه مقدار اطلاعات بیشتری بدید
گاهی ممکنه مشکل پیش بیاد
آیا مشکل پایدار هست؟
یا موقتی بوده؟
با چه اینترنتی کار میکنید؟

**Comment by oraclenik** [comment]
دوستان 1 ماه از آخرین پاسخ میگذره
اگر حل شده ایشیو رو ببندید 
سپاس گذارم

**Comment by ashkanRmk** [comment]
ممنون از پیگیری شما
