### ISSUE TITLE
Retrofit

### ISSUE THREAD

**Issue by xxzghxx** [freedomofdevelopers/fod#279]
implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
در گریدل ، بیلد نمیشوند لطفا Retrofit رو هم اد کنید

**Comment by behdad222** [comment]
این چیزی که نوشتیت اشتباه هست
ریپازیتوری‌هایی که رتورفیت توش هست قبلا اضافه شده
