### ISSUE TITLE
https://www.quora.com

### ISSUE THREAD

**Issue by xxzghxx** [freedomofdevelopers/fod#303]
https://www.quora.com

**Comment by behdad222** [comment]
quora تو ایران فیلتر هست
ما فقط امکان دور زدن تحریم رو فراهم میکنیم

**Comment by ghodsizadeh** [comment]
از کجا میشه تشخیص داد که تحریم هست یا فیلتر؟

**Comment by behdad222** [comment]
معمولا اگر تحریم باشه سایت باز میشه ولی میگه دسترسی ندارید
