### ISSUE TITLE
google-analytics.com problem

### ISSUE THREAD

**Issue by Azoic** [freedomofdevelopers/fod#320]
سایت google-analytics.com با پروکسی شما به هیچ عنوان باز نمیشه

**Comment by behdad222** [comment]
این پراکسی مناسب وب گردی نیست
این سایت ریکوست‌هایی به دامنه‌های دیگه هم میزنه که ازشون پشتیبانی نمیکنیم
میتونید اون دامنه‌هارو هم پیدا کنید تا اضفافه کنیمش

**Comment by Azoic** [comment]
منظور من وبگردی نیست
برای سایت هایی که گوگل آنالایتیکز کار کردم مدام خطا میداد و فکر میکردم مشکل از طرف منه و نهایت فهمیدم که مشکل از پراکسی بود

دامنه فوق به دامنه https://www.google.com/analytics ریدایرکت میشه که البته تحریم هم نیست و بدون ریدایرکت باز میشه اما موقعی که پراکسی وصل باشه این ریدایرکت ارور میده (مگر اینکه ریدایرکت از قبل در مرورگر کش شده باشه)

به نظر من بهتره دامنه فوق رو از لیست حذف کنید همان دامنه analytics.google.com به تنهایی کفایت میکنه

**Comment by behdad222** [comment]
google.com رو نمیتونیم اضافه کنیم
میتونید پراکسی رو جوری تنظیم کنید که فقط دامنه‌هایی که ما پشتیبانی میکنیم رو از fod رد کنه

**Comment by Azoic** [comment]
نه منظورمو درست متوجه نشدید
عرض کردم که دامنه 
analytics.google.com
را از لیست حذف کنید، چرا که در لیست تحریم قرار نداره

**Comment by behdad222** [comment]
مهم نیست
