### ISSUE TITLE
قرار دادن وبسایت گوگل

### ISSUE THREAD

**Issue by HamedDaneshnia** [freedomofdevelopers/fod#365]
لطفا وبسایت گوگل را هم در لیست قرار دهید. چون برای جستجو مشکلاتمان باید در گوگل سرچ کنیم و در نتایج به سایت های تحریم شده میخوریم . اینطوری هر بار باید پروکسی را خاموش و روشن کنیم .
اگر وبسایت گوگل در لیست قرار بگیرد، وقتی که پروکسی فعال است هم میتوانیم به کار خودمون ادامه بدهیم

سپاس

**Comment by behdad222** [comment]
نمیتونیم
میتونید فقط برخی دامین‌ها که تحریم هست رو از پراکسی رد کنید

توضیحاتی در این مورد داده شده
