### ISSUE TITLE
add kaggle website

### ISSUE THREAD

**Issue by kazemsamiei** [freedomofdevelopers/fod#366]
کگل بزرگ‌ترین جامعه مهندسان داده و یادگیری ماشینی است. Kaggle با ارائه خدمات یادگیری ماشین در حال حاضر یک پلت فرم داده عمومی، یک میز کار بر پایه ابر برای علوم داده و شکل کوتاه آموزش هوش مصنوعی ارائه می‌دهد.

لطفا به ليست دامين ها اضافه اش كنيد. با تشكر

**Comment by behdad222** [comment]
دامینش چیه؟

**Comment by behdad222** [comment]
یکی از دوستان مرج ریکوست داد اضافه شد
