### ISSUE TITLE
لیستی از سایتها هنگام اختلال

### ISSUE THREAD

**Issue by mostafanastary** [freedomofdevelopers/fod#370]
سلام. با توجه به شرایط قطعی اینترنت در مقاطعی همچون آشوب های خیابانی، دسترسی به سایتهایی که ما را تحریم هم نکرده اند، امکان پذیر نیست. لطفا این سایتها را نیز اضافه کنید.
همچون:

https://google.com
https://gmail.com
https://stackoverflow.com/
و...

**Comment by behdad222** [comment]
اون موقع مارو خفت میکنند
چنین امکانی رو نداریم

**Comment by mostafanastary** [comment]
خخخ، نه ان شاء الله
لااقل شما
https://stackoverflow.com/
https://99designs.com/
رو اضافه کن، این سایتها که موردی نداره!
