### ISSUE TITLE
مشکل اینترنت دانشگاه با گیت هاب

### ISSUE THREAD

**Issue by fakhamatia** [freedomofdevelopers/fod#375]
سایت گیت هاب با اینترنت دانشگاه باز نمیشه ارور `ERR_TIMED_OUT` میده و با FOD هم ارور `ERR_TUNNEL_CONNECTION_FAILED`

**Comment by Azoic** [comment]
کلا گیت با این پروکسی بزور بالا میاد

**Comment by behdad222** [comment]
دوباره چک کنید ببینید مشکل حل شده

**Comment by fakhamatia** [comment]
نه متاسفانه ارور `ERR_TIMED_OUT` میده
خیلی کم گاهی اوقات باز میشه ولی یهو باز ارور میده

**Comment by oraclenik** [comment]
تحت حمله هستش سرویس دوست عزیز
سعی داریم مشکل زو کمتر کنیم
ولی تا الان از ۲۵هزار IP متفاوت DDoS شده سرویس وادامه هم داره
و به دلیل ماهیت سرویس نمیشه از سرویس هایی مثل کلادفلر براش استفاده کرد
