### ISSUE TITLE
درست کردن پروکسی

### ISSUE THREAD

**Issue by RezaAlizadeh98** [freedomofdevelopers/fod#377]
سلام خسته نباشید میشه یه منبعی یا اموزشی معرفی کنید .
که بتونم برا خودم یه دونه از این پروکسی ها بسازم

**Comment by fakhamatia** [comment]
@RezaAlizadeh98 [https://github.com/oraclenik/proxyTutorial](https://github.com/oraclenik/proxyTutorial)

**Comment by RezaAlizadeh98** [comment]
ممنون از راهنماییتون 
من میخونم و خودمم یه سرچ میکنم  ببینم فیلم اموزشی و اینا در این مورد پیدا کردم لینکشو اینجا میزارم...
