### ISSUE TITLE
sourceforge مشکل با سایت 

### ISSUE THREAD

**Issue by fakhamatia** [freedomofdevelopers/fod#382]
سایت sourceforge دسترسی برای دانلود نمیده
از افزونه SwitchyOmega استفاده میکنم
اون آیپی هم برای سیستم من نیست
![Screenshot from 2019-12-06 18-21-31](https://user-images.githubusercontent.com/20030910/70331785-75735180-1855-11ea-9e2f-27fe11ca7610.png)

**Comment by behdad222** [comment]
یک ساعت دیگه دوباره چک کنید

**Comment by fakhamatia** [comment]
تست شد و مشکل حل شده بود
