### ISSUE TITLE
مشکل با api جستجو algolia.net

### ISSUE THREAD

**Issue by mh828** [freedomofdevelopers/fod#386]
سلام ، همونطور که میدونید الان خیلی از سایتها، مثل bootstrap، fontawesome، laravel و ... از api algolia.net استفاده میکنند که متاسفانه کشور مارو فیلتر کرده، لطفاً آنها را هم به لیست سایتهای تحت پوشش اضافه کنید

**Comment by behdad222** [comment]
سلام
لطفا دامین رو بگید

**Comment by mh828** [comment]
سلام
*.algolianet.com
*.algolia.net
