### ISSUE TITLE
مشکل سایت medium

### ISSUE THREAD

**Issue by fakhamatia** [freedomofdevelopers/fod#408]
تقریبا بیشتر لینک های سایت medium باز نمیشن
[نمونه](https://medium.com/@simplyafia/how-to-create-a-login-system-with-remember-me-feature-in-php-6c5c98e5fbb0)
```
This site can’t be reachedThe webpage at https://medium.com/@simplyafia/how-to-create-a-login-system-with-remember-me-feature-in-php-6c5c98e5fbb0 might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED
```

**Comment by behdad222** [comment]
سرویس fod برای وب گردی مناسب نیست
ولی من تو دیدن این صفحه با fod مشکل نداشتم
در هر صورت یه چندتا اروری که بود تا یک ساعت دیگه برطرف میشه
ممکنه برای شما تاثیر گزار بوده باشه
