### ISSUE TITLE
Why fod?

### ISSUE THREAD

**Issue by i3130002** [freedomofdevelopers/fod#412]
Having Shecan.ir/Begzar.ir as in #129 are you still maintaining this repository? Why is that?

**Comment by aminvakil** [comment]
It's not just as simple as that, I myself use it in some companies which shecan or any other public dns server or paid private dns server cannot satisfy its users and the bandwidth that they're using, so it's mandatory to setup a customized dns server which doesn't have any restriction on speed and it's up to ourselves if we want to add a domain or remove a domain.

Also I've used shecan once and after 3 minutes its speed dropped to 100KB/s, I don't think it can be used in enterprise solutions.

**Comment by behdad222** [comment]
@i3130002 
Shecan/Begzar is not safe
