### ISSUE TITLE
Android Studio version 3.6.3

### ISSUE THREAD

**Issue by mahjalili** [freedomofdevelopers/fod#414]
سلام
امروز استدیوی من آپدیت شد به 3.6.3 و بعدش دیگه گرادل سینک نمیکنه؟ قبلش همه چیز خوب بود

Gradle sync failed: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Request blocked by Privoxy"

**Comment by behdad222** [comment]
من تو همین نسخه اندروید استادیو مشکل ندارم
اگر بتونی بگی به چه دامینی ریکوست میزنه میتونیم مشکل رو حل کنیم
