### ISSUE TITLE
remove google-analytics.com

### ISSUE THREAD

**Issue by Azoic** [freedomofdevelopers/fod#420]
دامنه فوق مربوط به جمع آوری اطلاعات بازدید از سایت ها هست اولا تحریم نیست دوما وقتی پروکسی میشه ارور میده (بخاطر تفاوت آی پی بازدید کننده از سایت و دامنه فوق)
لطفا از لیست دامنه حذف کنید
ضمن اینکه من چک کردم دیدم این دامنه سه بار در لیست تکرار شده !

**Comment by behdad222** [comment]
بدونش مشکلی ایجاد نمیکنه
