### ISSUE TITLE
اضافه‌کردن سرویس

### ISSUE THREAD

**Issue by xmha97** [freedomofdevelopers/fod#426]
سلام خدمت باعث و بانی این پروژه
آیا میتونم سرویسی رو اضافه کنم که ایران رو تحریم کرده اما ربطی به برنامه‌نویسی و توسعه‌ی نرم‌افزار نداره؟

**Comment by behdad222** [comment]
اضافه کن
مشکلی نیست

**Comment by xmha97** [comment]
ممنون
