### ISSUE TITLE
Flutter pub get 

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [freedomofdevelopers/fod#430]

**Comment by behdad222** [comment]
میتونی بگی به چه دامینی ریکوست میزنه؟

**Comment by Morteza-Rastgoo** [comment]
نمی‌دونم والا
سر در نیاوردم

**Comment by Morteza-Rastgoo** [comment]
https://pub.dartlang.org/

**Comment by Morteza-Rastgoo** [comment]
Pub get fails from behind a corporate firewall
From the command line, pub honors the http_proxy and https_proxy environment variables. You can set the proxy server environment variable as follows.

On Linux/macOS:

 export https_proxy=hostname:port
On Windows Command Prompt:

 set https_proxy=hostname:port
On Windows PowerShell:

 $Env:https_proxy="hostname:port"
If the proxy requires credentials, you can set them as follows.

On Linux/macOS:

 export https_proxy=username:password@hostname:port
On Windows Command Prompt:

 set https_proxy=username:password@hostname:port
On Windows PowerShell:

 $Env:https_proxy="username:password@hostname:port"

**Comment by Morteza-Rastgoo** [comment]
برای چینی ها که فیلتره این کارو کردن که ریپازیتوری جدا درست کردن:
https://flutter.dev/community/china

‍‍‍‍‍‍```
 export PUB_HOSTED_URL=https://pub.flutter-io.cn
 export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```

**Comment by Morteza-Rastgoo** [comment]
ممنون که زحمتش رو کشیدید
اگر هم یه راهنما برای ست کردنش تو فلاتر بذارید تو صفحه اصلی ریپو عالی میشه

**Comment by behdad222** [comment]
@Morteza-Rastgoo میتونی اضافه کنی؟
