### ISSUE TITLE
اضافه کردن Etcher

### ISSUE THREAD

**Issue by fakhamatia** [freedomofdevelopers/fod#431]
میشه لطفا آدرس ریپو Etcher رو اضافه کنید؟
تحریم کرده نمیشه دانلود کرد ازش برای apt اوبونتو
[https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64](https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64)

**Comment by behdad222** [comment]
دامینش چی هست؟

**Comment by fakhamatia** [comment]
فکر می کنم این اصل کار باشه
‍`balena.io`
برای اوبونتو این هست کاملش
`"deb https://deb.etcher.io stable etcher"`
