### ISSUE TITLE
don't connect to server عدم اتصال به سرور

### ISSUE THREAD

**Issue by DigiGostar** [freedomofdevelopers/fod#432]
show error 403 and don't connect to server !
نمایش خطای 403 و و صل نشدن به سرور !

screen shot :
http://uupload.ir/files/47gu_untitled.png

**Comment by DigiGostar** [comment]
screen shot : 
[http://uupload.ir/files/47gu_untitled.png](url)

**Comment by behdad222** [comment]
@DigiGostar 
چه دامینی رو تست کردی که این ارور رو داد؟

**Comment by DigiGostar** [comment]
https://google.com

اصلا چند ماهی هست دیگ نیمتونم از پروکسی شما استفاده کنم و خطا میده و گریدل هم به مشکل میخوره

**Comment by behdad222** [comment]
google.com رو به تنهایی ساپورت نمیکنیم
