### ISSUE TITLE
https://gitlab.freedesktop.org/gstreamer/ isn't supported

### ISSUE THREAD

**Issue by persianpros** [freedomofdevelopers/fod#441]
Hi guys,

You should be familiar with GStreamer project I think: https://gstreamer.freedesktop.org

They use gitlab somehow but with different URL scheme, example: git://anongit.freedesktop.org/gstreamer/gst-libav

Would you please support these kind of URLs?

Regards,
Persian Prince

**Comment by persianpros** [comment]
Is everything ok?

No even the normal gitlab.com won't work for me:

`Secure Connection Failed

An error occurred during a connection to gitlab.freedesktop.org. PR_END_OF_FILE_ERROR`

**Comment by behdad222** [comment]
@persianpros 
check again
