### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by babakyakhchali** [freedomofdevelopers/fod#447]
Hi
thanks for services to developers
today suddenly I'm getting:
fatal: unable to access 'https://github.com/xxx/xxx/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by persianpros** [comment]
Yep nothing works ...

**Comment by behdad222** [comment]
@babakyakhchali @persianpros 
check again

**Comment by persianpros** [comment]
It's ok :+1: 

Thanks a lot.
