### ISSUE TITLE
add kinsta.com

### ISSUE THREAD

**Issue by Azoic** [freedomofdevelopers/fod#449]

**Comment by behdad222** [comment]
دقیقتر میگی چه میکنه

**Comment by Azoic** [comment]
یه سایت خدماتی برای وب هست منتهی بیشتر مطالب آموزشی که میگذاره به درد من میخوره
مثل این:
https://kinsta.com/blog/sucuri-vs-wordfence/

**Comment by Azoic** [comment]
🙄
