### ISSUE TITLE
add graph.facebook.com

### ISSUE THREAD

**Issue by ziaratban** [freedomofdevelopers/fod#450]
salam.
bi zahmat in address ra ham ezafe konid.

https://developers.facebook.com/docs/graph-api

mamnon.

**Comment by aminvakil** [comment]
README:

توجه داشته باشید که این سرویس فقط برای دور زدن تحریم‌ها ساخته شده و سایت‌هایی که تحریم نکردند یا فیلتر شدن از این سرویس قابل دسترسی نیست.

**Comment by behdad222** [comment]
> salam.
> bi zahmat in address ra ham ezafe konid.
> 
> https://developers.facebook.com/docs/graph-api
> 
> mamnon.

بیا خودمون رو وارد این بازی خطرناک نکنیم

**Comment by ziaratban** [comment]
> 
> 
> > salam.
> > bi zahmat in address ra ham ezafe konid.
> > https://developers.facebook.com/docs/graph-api
> > mamnon.
> 
> بیا خودمون رو وارد این بازی خطرناک نکنیم

ایسنتاگرام که فیلتر نیست و برای دسترسی به خدمات اینستاگرام شما مجبور هستین از گراف فیسبوک استفاده کنین.

درواقع این خدمات آمیخته شده اند.

**Comment by behdad222** [comment]
@oraclenik 
نظر تو چیه؟
