### ISSUE TITLE
bintray.com

### ISSUE THREAD

**Issue by Mds92** [freedomofdevelopers/fod#465]
Hello and thanks for you great work.

`bintray.com` is also blocked Iran and we need to access it for developing in `Flutter`.
With your proxy I'm getting 403-Forbidden to access it. Please add it to your list.

```
Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'. Received status code 403 from server: Forbidden
```

Thanks

**Comment by behdad222** [comment]
This is not our problem.

**Comment by Mds92** [comment]
But I'm getting this error whenever used fodev.org:8118 proxy !
I'm using IranCell 4G

**Comment by behdad222** [comment]
This is the problem of Bintray.

**Comment by fakhamatia** [comment]
![image](https://user-images.githubusercontent.com/20030910/116132609-fb11ce80-a6e2-11eb-86f7-c9e5701d8b9b.png)

![image](https://user-images.githubusercontent.com/20030910/116132940-5cd23880-a6e3-11eb-954d-f370adb457fa.png)

![image](https://user-images.githubusercontent.com/20030910/116133163-a3279780-a6e3-11eb-8d0d-3b4d4a1a7a8f.png)

هم توی apt هم توی کروم باز نمیشه ۴۰۳ میده
از fod هم استفاده میکنم
