### ISSUE TITLE
plz add https://developer.huawei.com/repo/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom

### ISSUE THREAD

**Issue by alirezasafdari** [freedomofdevelopers/fod#470]
لطفا این سایت رو هم اضافه کنید
https://developer.huawei.com/repo/com/huawei/hms/push/5.0.2.300/push-
https://developer.huawei.com/repo/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom

**Comment by alisafavi** [comment]
شما؟
