### ISSUE TITLE
Android SDK Manager doesn't get packages

### ISSUE THREAD

**Issue by MohammadMD1383** [freedomofdevelopers/fod#495]
Android studio 4.2.1

همه‌ی موارد دیگه از جمله گریدل و … با این پروکسی کار میکنن ولی پکیج های sdk همچنان پشت تحریمه

![image](https://user-images.githubusercontent.com/69088224/118268321-7c82a280-b4d2-11eb-94f1-da1f3334e453.png)
![image](https://user-images.githubusercontent.com/69088224/118268346-86a4a100-b4d2-11eb-9d12-fa86b3be76de.png)

**Comment by behdad222** [comment]
پورت رو فارسی وارد نکنید

**Comment by MohammadMD1383** [comment]
نه من پورت رو فارسی نمیزنم
به خاطر locale سیستمم اونجوری خوودش نشون میده
الان با شکن هم امتحان میکنم بازم نمیتونم لیست sdk رو بگیرم

**Comment by MohammadMD1383** [comment]
مشکل از پراکسی نبود
به نظر میرسه نسخه جدید اندروید استودیو تو این قسمت باگ داره
AS 4.2.1

**Comment by rezazarchi** [comment]
مشکل دقیقا از Regional format سیستم عامل شماست. اون رو از فارسی به انگلیسی US تغییر بدین تا مشکلتون حل بشه
