### ISSUE TITLE
مشکل در اضافه کردن کلید با fod

### ISSUE THREAD

**Issue by fakhamatia** [freedomofdevelopers/fod#510]
توی ترمینال وقتی fod رو فعال میکنم هیچ اتفاقی نمیوفته
توی حالت های دیگه برای داکر خوب کار میکنه ولی توی این قسمت نه
![image](https://user-images.githubusercontent.com/20030910/121346959-f1af8f00-c93b-11eb-8f77-a1d3d1359d8c.png)

**Comment by behdad222** [comment]
از پراکسی خود `curl` یا از `proxychains` استفاده کن

**Comment by fakhamatia** [comment]
اینجوری زدم اوکی شد
``` bash
curl -fsSL https://download.docker.com/linux/ubuntu/gpg --proxy http://fodev.org:8118 | sudo apt-key add -
```
