### ISSUE TITLE
add domains: 

### ISSUE THREAD

**Issue by MohammadRaziei** [freedomofdevelopers/fod#515]
hi, please add these domain: https://ipinfo.io/ , https://ifconfig.co/   ,    https://ipwhois.app
thanks

**Comment by MohammadRaziei** [comment]
and https://ifconfig.co/

**Comment by behdad222** [comment]
چرا اینا رو می‌خوای اضافه کنی؟
در هر صورت ip پراکسی fod رو میده
نه ip خودت رو

**Comment by MohammadRaziei** [comment]
تا مطمین شم تو لینوکس تو ترمینالش پروکسی فعال شده

**Comment by MohammadRaziei** [comment]
چون تو ترمینال میخوام چک کنم دامین رو  این سایت ها رو دسترسی ندارم دیگه چون ریدایرکت نمیشه! و دقیقا میخوام اونارو چک کنم
