### ISSUE TITLE
problem accessing gitlab.com

### ISSUE THREAD

**Issue by ali-shamakhi** [freedomofdevelopers/fod#561]
There is a problem accessing gitlab.com, requests do not get a response.

**Comment by fakhamatia** [comment]
`fatal: unable to access 'https://gitlab.com/*/*.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.`

**Comment by reza-madani** [comment]
I have the same issue

**Comment by Sifb71** [comment]
i have the same issue too,Something does not seem to be working properly!

**Comment by vispamir** [comment]
I have the same issue.
I think Gitlab.com has detected and blocked this proxy.

**Comment by ali-shamakhi** [comment]
Since I was using this service for a while and it was perfect for me, I have just donated hoping to help the devs fix the problem. I suggest anyone looking towards this issue being fixed to do the same :)

**Comment by mostafaznv** [comment]
من هم مبلغی رو پرداخت کردم. امیدوارم که بزودی مشکل رو برطرف کنن

**Comment by masoud-msk** [comment]
@behdad222

**Comment by behdad222** [comment]
@oraclenik 
درسته گیت‌لب حدود ۱-۲ هفته هست که متوجه شدم بستتمون
میتونی یه سرور بگیری؟

**Comment by bmrbehnam** [comment]
اره قطع شده

**Comment by behdad222** [comment]
همچنان داریم ور میریم

**Comment by amirmms** [comment]
same

```
nc: Proxy error: "HTTP/1.0 403 Request blocked by Privoxy"
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**Comment by behdad222** [comment]
@amirmms 
این یه مشکل دیگست داری به دامین ریکوست میزنی که جزو وایت لیست نیست
دامین رو پیدا کن و مرج ریکوست بده  یا ایشو بزن براش

**Comment by oraclenik** [comment]
![image](https://user-images.githubusercontent.com/3889238/151703058-e844dd89-4376-488e-b91d-fa47bb7849fb.png)

It got resolved for now(temporary)
I will work on something that addresses this issue for a longer time.

**Comment by behdad222** [comment]
مشکل  حل شده
