### ISSUE TITLE
problem with docker

### ISSUE THREAD

**Issue by smzerehpoush** [freedomofdevelopers/fod#568]
when running command:
```sudo apt-get update```
it say's:

Failed to fetch https://download.docker.com/linux/ubuntu/dists/focal/InRelease  403  Forbidden [IP: 65.9.61.77 443]

**Comment by behdad222** [comment]
هنوز هم مشکل هست؟

**Comment by smzerehpoush** [comment]
به نظر رفع شده  
ممنون
