### ISSUE TITLE
مشکل با رجیستر کردن gitlab-runner

### ISSUE THREAD

**Issue by Ham3D** [freedomofdevelopers/fod#585]
با این پروکسی گیت لب رانر رجیستر نمیشه.
بعد از فعال کردن پروکسی و اجرای دستور رجیستر کردن گیت لب رانر خطای زیر رو میده :
ERROR: Registering runner... failed                 runner=GR134894 status=couldn't execute POST against https://gitlab.com/api/v4/runners: Post "https://gitlab.com/api/v4/runners": proxyconnect tcp: net/http: TLS handshake timeout
PANIC: Failed to register the runner. You may be having network problems.

**Comment by behdad222** [comment]
رانر رو می‌خوایید به خود گیت‌لب اضافه کنید؟
