### ISSUE TITLE
Anchor.FM

### ISSUE THREAD

**Issue by xmha97** [freedomofdevelopers/fod#594]
سلام، اپ‌های پادگیر، پادکست‌ها را از CDNهای مختلف پخش می‌کنن و از آنجایی که ۹۰ درصد پادکست‌های ایرانی در انکر هاست می‌شوند (چون رایگانه)، هیچ کدوم از اپ‌های پادگیر عملکرد مناسبی ندارند، لطفاً انکر را به لیست‌تون اضافه کنید.
https://anchor.fm/plato32/episodes/ep-ej02nj
![Screenshot_2022-04-01-08-38-57-834_org mozilla firefox](https://user-images.githubusercontent.com/23485114/161193750-481a5499-d96f-446e-bb50-11761b041c79.jpg)
این ایشو احتمالا در بر گیرنده‌ی این ایشو است: #479

**Comment by behdad222** [comment]
بعید میدونم به اسپاتیفای ربط داشته باشه
اسپاتیفای پادکست رو تو خودش هاست میکنه
