### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by amirmms** [freedomofdevelopers/fod#640]
سلام
برای نصب کامپوزر در لاراول خطای زیر میده :

Failed to download vlucas/phpdotenv from dist: curl error 28 while downloading https://api.github.com/repos/vlucas/phpdotenv/zipball/264dce589e7ce37a7ba99cb901eed8249fbec92f: SSL connection timeout

**Comment by behdad222** [comment]
احتمالا یه مشکل موقتی بوده
