### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by rkarimi88** [freedomofdevelopers/fod#641]
Hi
I was using the Proxy Settings in my Android Studio for the past 10 months and it was working like a charm... till 2 days ago.
I cannot sync my Android Studio anymore. Is there any alternative solution?
Thanks in advance.

**Comment by behdad222** [comment]
Can you tell me what domain has the problem?

**Comment by mh12** [comment]
منم چنین مشکلی خوردم، از هفته گذشته نه پروکسی fodev و نه dns هایی که برای این موضوع معرفی شده بود کار نمیکنه.
دولوپر اندروید نیستم، منتهی برای بررسی یک کد خواستم سینک کنم که در گریدل مشکل خوردم.
و برای حل مشکلم روی سرور و به صورت موقت گوگل رو میرور کردم و مشکل حل شد.
البته به صورت موقت اینکارو کردم و واقعا هم نمی‌دونم روش درستیه یا نه و اینکه اینجا هم مطرحش میکنم درست باشه یا نه.

توی repositories ها اضافه کنین.

`
    repositories {
        
     ...

        maven {
            url "https://aiburger.ir/dl/android/maven2"
        }

     ...

    }`

نمی‌دونم در مسئله شما مشکل رو حل میکنه، اما امیدوارم نتیجه بخش باشه.
* فقط این رو تاکید کنم که به صورت موقت راه انداختم و ترافیک زیادی روی این سرور ندارم، ممکنه از کار بیفته.

**Comment by mh12** [comment]
> Hi I was using the Proxy Settings in my Android Studio for the past 10 months and it was working like a charm... till 2 days ago. I cannot sync my Android Studio anymore. Is there any alternative solution? Thanks in advance.




منم چنین مشکلی خوردم، از هفته گذشته نه پروکسی fodev و نه dns هایی که برای این موضوع معرفی شده بود کار نمیکنه.
دولوپر اندروید نیستم، منتهی برای بررسی یک کد خواستم سینک کنم که در گریدل مشکل خوردم.
و برای حل مشکلم روی سرور و به صورت موقت گوگل رو میرور کردم و مشکل حل شد.
البته به صورت موقت اینکارو کردم و واقعا هم نمی‌دونم روش درستیه یا نه و اینکه اینجا هم مطرحش میکنم درست باشه یا نه.

توی repositories اضافه کنین.

`repositories {
        
     ...

        maven {
            url "https://aiburger.ir/dl/android/maven2"
        }

     ...

    }`

نمی‌دونم در مسئله شما مشکل رو حل میکنه، اما امیدوارم نتیجه بخش باشه.
* فقط این رو تاکید کنم که به صورت موقت راه انداختم و ترافیک زیادی روی این سرور ندارم، ممکنه از کار بیفته.

**Comment by rkarimi88** [comment]
> Can you tell me what domain has the problem?

سلام.
ساده‌ترین سینک رو در گریدل انجام نمیده. یعنی مثلا الان برای سینک recyclerview مشکل داره. دیگه نمی‌تونم پروژه جدید ایجاد کنم.

**Comment by rkarimi88** [comment]
> > Hi I was using the Proxy Settings in my Android Studio for the past 10 months and it was working like a charm... till 2 days ago. I cannot sync my Android Studio anymore. Is there any alternative solution? Thanks in advance.
> 
> منم چنین مشکلی خوردم، از هفته گذشته نه پروکسی fodev و نه dns هایی که برای این موضوع معرفی شده بود کار نمیکنه. دولوپر اندروید نیستم، منتهی برای بررسی یک کد خواستم سینک کنم که در گریدل مشکل خوردم. و برای حل مشکلم روی سرور و به صورت موقت گوگل رو میرور کردم و مشکل حل شد. البته به صورت موقت اینکارو کردم و واقعا هم نمی‌دونم روش درستیه یا نه و اینکه اینجا هم مطرحش میکنم درست باشه یا نه.
> 
> توی repositories اضافه کنین.
> 
> `repositories {
> 
> ```
>  ...
> 
>     maven {
>         url "https://aiburger.ir/dl/android/maven2"
>     }
> 
>  ...
> 
> }`
> ```
> 
> نمی‌دونم در مسئله شما مشکل رو حل میکنه، اما امیدوارم نتیجه بخش باشه.
> 
> * فقط این رو تاکید کنم که به صورت موقت راه انداختم و ترافیک زیادی روی این سرور ندارم، ممکنه از کار بیفته.


سلام.
خیلی ممنونم از راهنمایی شما، اما متاسفانه کار نکرد.. فکر کنم همون‌طور که گفتید سرور از کار افتاده.
بازهم از توجه و وقتی که گذاشتید سپاسگزارم.

**Comment by hamidb80** [comment]
منم ازش استفاده میکردم ولی امروز دیگه کار نمیکنه

**Comment by hamidb80** [comment]
من الان چک کردم درست شده

**Comment by rkarimi88** [comment]
> من الان چک کردم درست شده

سلام
بله دقیقا برای من هم الان درست شد :)
ممنون
