### ISSUE TITLE
Are the services working?

### ISSUE THREAD

**Issue by pouriaSharifi** [freedomofdevelopers/fod#645]
من چند تا از سرور هام به مشکل خورده و حس میکنم مشکل از پروکسی هستش ؟

**Comment by kooshan75** [comment]
منم راستش توی کار کردن با گیت به مشکل خوردم چندین جا که حدس میزنم مربوط به همین باشه (شایدم اینترنت داغون ایران) چون قبلا وقتی fod رو enable می‌کردم حل میشد:

```
fatal: unable to access 'https://gitlab.com/{my_repo}': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Comment by Sifb71** [comment]
سلام. بله به نظر کار نمی کنه. ما هم توی کار با گیت لب به شدت به مشکل خوردیم. ممنون میشم دوستان اگه راهکاری سراغ دارید اینجا با ما هم درمیون بزارید.

**Comment by pouriaSharifi** [comment]
سلام من تونستم مشکلم رو با تنظیم شکن حل کنم 
https://shecan.ir/
خواستید از این استفاده کنید دوستان تا مشکل این پروکسی حل بشه

**Comment by PhantomRex123** [comment]
> سلام من تونستم مشکلم رو با تنظیم شکن حل کنم https://shecan.ir/ خواستید از این استفاده کنید دوستان تا مشکل این پروکسی حل بشه

NuGet هم کار می کنه؟

**Comment by Sifb71** [comment]
آیا اگر شکن رو روی سرور اضافه کنیم، مشکلی برای شبکه به وجود نخواهد آمد؟

**Comment by pouriaSharifi** [comment]
@Sifb71 من توی قسمتی که داکر بیلد نیاز داره پکیج هایی رو نصب کنه شکن رو اضافه کردم نه کل سرور

**Comment by behdad222** [comment]
یه مقدار اختلال داشتیم
همون روزها باید مشکل حل شده باشه
و فعلا هم همه چی خوب کار میکنه

**Comment by behdad222** [comment]
@Sifb71 
الان دوباره خرابه
سرورش فیلتر شد
درستش میکنیم
