### ISSUE TITLE
connection time out & 

### ISSUE THREAD

**Issue by alirhn** [freedomofdevelopers/fod#654]
سلام، تا دیروز وصل می‌شد ولی این ارور رو میداد موقع build کردن ولی امروز اصلا connection time out  میداد، ارور دیروز: 
Could not GET 'https://sdk.uxcam.com/android/com/uxcam/uxcam/3.3.7/uxcam-3.3.7.pom'. Received status code 403 from server: Request blocked by Privoxy

**Comment by behdad222** [comment]
احتمالا مشکل موقتی بوده  
اگر همچنان مشکل هست بگید
