### ISSUE TITLE
از کار افتادن در اندروید استودیو

### ISSUE THREAD

**Issue by abbasalim** [freedomofdevelopers/fod#666]
سلام . متاسفانه اندروید استودیو چند روزی هست که دیگه کار نمیکنه و جالبه که خطای ۴۰۴ بجای ۴۰۳ میده :(((((( مک و ویندوز

**Comment by javaherisaber** [comment]
@abbasalim 
من هم مشکل 404 رو چند روزه دارم موقع بیلد گرفتن
تونستید راهکاری پیدا کنید؟

**Comment by Mohsents** [comment]
من خطای Connection refused رو میگیرم. علتش چیه؟

**Comment by abbasalim** [comment]
کلا مثل اینکه گوگل خیلی سخت گیریش بیشتر کرده. من geph یکبار برام جواب داد. v2ray اگه trojan ش رو بزنی جواب میده
. اینترنتهای مختلف هم فرق میکنه وضعیتش

**Comment by behdad222** [comment]
ببخشید دیر جواب دادم
ممکنه مشکل موقت بوده باشه
فعلا مشکلی نیست
اگر خطا میده url که ارور میده رو بگید

**Comment by muhammadali-karami** [comment]
> ببخشید دیر جواب دادم ممکنه مشکل موقت بوده باشه فعلا مشکلی نیست اگر خطا میده url که ارور میده رو بگید

سلام
Failed to resolve: com.github.smarteist:autoimageslider:1.4.0
به 
9:36 AM	Gradle sync failed: Could not GET 'https://jcenter.bintray.com/androidx/navigation/navigation-safe-args-gradle-plugin/2.5.1/navigation-safe-args-gradle-plugin-2.5.1.pom'. Received status code 403 from server: Forbidden
هم گیر میده؛ در کل فکر کنم با jCenter() اکی نیست.

**Comment by abbasalim** [comment]
> @abbasalim من هم مشکل 404 رو چند روزه دارم موقع بیلد گرفتن تونستید راهکاری پیدا کنید؟

وی ۲ ری روش تروجان جواب میده. شکن و 403 هم بگیر نگیر دارن گاهی جواب میدن. گاهی نمیدن
